apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cllr926gf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cllr926gf-python 
  name: cllr926gf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cllr926gf-python 
