apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cllr926gf-python 
  janus-idp.io/tekton: cllr926gf-python
  backstage.io/kubernetes-id: cllr926gf-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cllr926gf-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml