apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cllr926gf-python-gitops
  description: This is GitOps manifest for cllr926gf-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=cllr926gf-python
    backstage.io/kubernetes-id: cllr926gf-python 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: cllr926gf-python-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:cllr926gf-python
